# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ddos_tasarim_grup1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 540)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 540))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 540))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: rgb(180, 180, 180)\n"
"}\n"
"QGroupBox{\n"
"    background-color: rgb(255, 131, 6);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"QListWidget{\n"
"    color : rgb(255,255,255);\n"
"    font-size : 18px;\n"
"}\n"
"QListWidget::item:selected{\n"
"    background: rgb(239, 41, 41);\n"
"    color : black;\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    border-radius:5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#btn_ac:hover:!pressed{\n"
"    background-color: rgb(0,255,0);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius:5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton#btn_kapat:hover:!pressed{\n"
"    background-color: rgb(255,0,0);\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"border-radius:5px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover:!pressed{\n"
"  border: 2px solid rgb(46, 52, 54);\n"
"    color :rgb(0,0,0);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QLabel{\n"
"    \n"
"    color : black;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(255, 131, 6);\n"
"}\n"
"QLineEdit{\n"
"    font-size : 18px;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(255, 131, 6);\n"
"    color : white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(11, 11, 978, 60))
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 60))
        self.groupBox_2.setStyleSheet("")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 271, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.tbl_rapor = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_rapor.setGeometry(QtCore.QRect(219, 79, 771, 421))
        self.tbl_rapor.setObjectName("tbl_rapor")
        self.tbl_rapor.setColumnCount(0)
        self.tbl_rapor.setRowCount(0)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(12, 79, 200, 421))
        self.groupBox.setMinimumSize(QtCore.QSize(200, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 181, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_kullaniciBilgi = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_kullaniciBilgi.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_kullaniciBilgi.setFont(font)
        self.btn_kullaniciBilgi.setStyleSheet("")
        self.btn_kullaniciBilgi.setObjectName("btn_kullaniciBilgi")
        self.verticalLayout.addWidget(self.btn_kullaniciBilgi)
        self.btn_ac = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_ac.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_ac.setFont(font)
        self.btn_ac.setStyleSheet("")
        self.btn_ac.setObjectName("btn_ac")
        self.verticalLayout.addWidget(self.btn_ac)
        self.btn_kapat = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_kapat.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_kapat.setFont(font)
        self.btn_kapat.setStyleSheet("")
        self.btn_kapat.setObjectName("btn_kapat")
        self.verticalLayout.addWidget(self.btn_kapat)
        self.btn_ticket = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_ticket.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_ticket.setFont(font)
        self.btn_ticket.setStyleSheet("")
        self.btn_ticket.setObjectName("btn_ticket")
        self.verticalLayout.addWidget(self.btn_ticket)
        self.btn_rapor = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_rapor.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_rapor.setFont(font)
        self.btn_rapor.setStyleSheet("")
        self.btn_rapor.setObjectName("btn_rapor")
        self.verticalLayout.addWidget(self.btn_rapor)
        self.btn_yardim = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btn_yardim.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_yardim.setFont(font)
        self.btn_yardim.setStyleSheet("")
        self.btn_yardim.setObjectName("btn_yardim")
        self.verticalLayout.addWidget(self.btn_yardim)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DDoS Mitigation With AI"))
        self.label.setText(_translate("MainWindow", "  DDoS Savunma Sistemi"))
        self.groupBox.setTitle(_translate("MainWindow", "İşlemler"))
        self.btn_kullaniciBilgi.setText(_translate("MainWindow", "Kullanıcı Bilgileri"))
        self.btn_ac.setText(_translate("MainWindow", "Aç"))
        self.btn_kapat.setText(_translate("MainWindow", "Kapat"))
        self.btn_ticket.setText(_translate("MainWindow", "Ticket Oluştur"))
        self.btn_rapor.setText(_translate("MainWindow", "Rapor"))
        self.btn_yardim.setText(_translate("MainWindow", "Yardım"))
